on: push
jobs:
 build:
  strategy:
   matrix:
    os: [ macos-latest, ubuntu-latest, windows-latest ]
  runs-on: ${{ matrix.os }} 
  steps: 
   - uses: actions/checkout@v4 
   - name: 'Set up JDK 1.17'     
     uses: actions/setup-java@v4
     with: 
      distribution: 'temurin'
      java-version: '17'
   - run: ./gradlew packageDistributionForCurrentOS
